name: Gradle Build (Mac)

on: [push]

jobs:
  Build:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [8, 11]
        gradle: [6.8.3, 6.7.1, 6.6.1, 6.5.1]
        ndk: [23.0.7123448, 22.0.7026061, 21.4.7075529, 20.1.5948944, 19.2.5345600]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle Wrapper
        run: gradle wrapper --gradle-version ${{ matrix.gradle }} --distribution-type bin
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${{ matrix.ndk }}" --sdk_root=${ANDROID_SDK_ROOT} --channel=3
      - name: Set NDK Default Version
        run: echo ${{ matrix.ndk }}> ${HOME}/test-ndk-version.txt
      - name: Build Plugin
        run: ./gradlew --info --stacktrace -Pversion=0.1.${{ github.run_number }} assemble :test
