name: Gradle build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [8, 11]
        gradle: [6.8.3, 6.7.1, 6.6.1, 6.5.1, 6.4.1, 6.3, 6.2.2, 6.1.1, 6.0.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle Wrapper
        run: gradle wrapper --gradle-version ${{ matrix.gradle }} --distribution-type bin
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;23.0.7123448" --sdk_root=${ANDROID_SDK_ROOT} --channel=3
      - name: Build Plugin
        run: ./gradlew --stacktrace -Pversion=0.1.${{ github.run_number }} assemble :test
